Improve formatting of cyclical dependency error reporting
This adds a line break between dependencies, since each line tends to be very long. It's easier to understand the cycle if the actual file names are grouped closer together into a column. This change adds a newline between each dependency in the cycle to better achieve that. It also adds space between the stacktrace below and the context above.

Previously:

Compilation failed Error: Cyclical dependency between files:
src/b.ts -> src/a.ts -> src/b.ts

Now:

Compilation failed Error:

Cyclical dependency between files:
src/b.ts ->
src/a.ts ->
src/b.ts

PiperOrigin-RevId: 291974463